version: '3.9'

services:
 wordpress:
  depends_on:
   - mariadb
  build: requirements/wordpress
  image: wordpress
  container_name: wordpress
  restart: always
  env_file: .env
  volumes:
   - wd:/var/www/html/
  networks:
   - inception
 
 mariadb:
  build: requirements/mariadb
  image: mariadb
  container_name: mariadb
  restart: always
  env_file: .env
  volumes:
    - db:/var/lib/mysql/
  networks:
   - inception

 nginx:
  depends_on:
   - wordpress
  build: requirements/nginx
  image: nginx
  container_name: nginx
  restart: always
  volumes:
   - wd:/var/www/html/
  ports:
   - "443:443"
  networks:
   - inception

volumes:
  wd:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/alpascal/data/wp
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/alpascal/data/db

networks:
 inception:
  driver: bridge
