version: '3'

services:
  nginx:
    depends_on:
      - wordpress
    hostname: alpascal
    build: requirements/nginx
    container_name: nginx
    restart: always
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    networks:
      - front
  
  wordpress:
    depends_on:
      - mariadb
    hostname: alpascal
    build: requirements/wordpress
    container_name: wordpress
    restart: always
    volumes:
      - wordpress:/var/www/html
    networks:
      - front
      - back

  mariadb:
    hostname: alpascal
    build: requirements/mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - db:/var/run/mysqld
    networks:
      - back

volumes:
  wordpress:
  db:

networks:
  front:
    driver: bridge
  back:
    driver: bridge
